### ISSUE TITLE
Can't build today - package "AS" does not exist?

### ISSUE THREAD

**Issue by xach** [ceramic/trivial-ws#4]
I get a package error when I try to build today. Do you know what might cause it to miss an "AS" package?

http://report.quicklisp.org/2017-02-22/failure-report/trivial-ws.html#trivial-ws-client has a log.

**Comment by quicklisp** [comment]
Joram Schrijver (mood on #lisp) found the answer - websocket-driver no longer depends-on cl-async, so trivial-ws should explicitly depend on it if it wants to use the AS package.

**Comment by eudoxia0** [comment]
Fixed!

**Comment by xach** [comment]
Same problem with trivial-ws-client remains.

**Comment by xach** [comment]
Any word on this?

**Comment by eudoxia0** [comment]
Fixed now
